### ISSUE TITLE
`tric init` generates `.htaccess` file with `deny from all`

### ISSUE THREAD

**Issue by juanfra** [the-events-calendar/tric#75]
When running `tric init` on a plugin an `.htaccess` file is created with `deny from all`. This affects some tests that use assets from the plugins, because a 403 is being returned. For plugins that also init common, the file can be found there as well.

**🎥 Screencast**
https://www.loom.com/share/d7b34e00a268425b86412c96ede88555

**Comment by lucatume** [comment]
Fixed in #76
